import { PROTOCOL_VERSION, type HarnessMeta } from "@handrail/harness-kit";

declare const __HANDRAIL_LIBRARY_VERSIONS__: Record<string, string>;

export const LIBRARY_ID = "shadcn";
export const ADAPTER_VERSION = "0.1.0";

/**
 * shadcn/ui is not installed, it is generated. There is no package version to
 * pin, so what identifies a result is the CLI that produced the code and the day
 * it did — plus the resolved versions of the libraries that code imports, which
 * the build injects as usual.
 */
export const GENERATOR = {
  cli: "shadcn@4.16.1",
  generatedOn: "2026-08-04",
  style: "new-york",
  command: "npx shadcn@4.16.1 add dialog dropdown-menu tabs accordion combobox",
} as const;

export function metaFor(component: string): HarnessMeta {
  return {
    protocolVersion: PROTOCOL_VERSION,
    library: LIBRARY_ID,
    libraryVersions: { ...__HANDRAIL_LIBRARY_VERSIONS__, [GENERATOR.cli]: GENERATOR.generatedOn },
    adapterVersion: ADAPTER_VERSION,
    component,
    notes:
      `Generated by ${GENERATOR.cli} on ${GENERATOR.generatedOn} using the "${GENERATOR.style}" style, ` +
      `via: ${GENERATOR.command}. The component source is copied into this repository unmodified — ` +
      "shadcn/ui is a code generator, not a dependency, so a result describes the code that CLI " +
      "produced on that date and nothing else. Dialog, menu, tabs and accordion are built on Radix; " +
      "the combobox is built on Base UI.",
  };
}
